steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'my-cloud-run-app',
        '--source', '.',
        '--region', 'us-central1',  
        '--platform', 'managed',
        '--allow-unauthenticated'
      ]

logsBucket: gs://talon-buck-01

